web/urls.py
from django.urls import path
from web.views import scrap, search, estimate

app_name = 'web'

urlpatterns = [
    path('', scrap, name='scrap'),
    path('search/', search, name='search'),
    path('estimate/', estimate, name='estimate'),
]

webscraping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models


# Create your models here.
class house(models.Model):
    id = models.AutoField(primary_key=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    rooms = models.CharField(max_length=100, blank=True, null=True)
    parking = models.CharField(max_length=100, blank=True, null=True)
    price = models.CharField(max_length=100, blank=True, null=True)
    metr = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.location

web/forms.py
from django import forms

from web.models import house


class filter_form(forms.ModelForm):
    class Meta:
        model = house
        fields = '__all__'

web/views.py
import pandas as pd

import numpy as np
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from web.forms import house
from bs4 import BeautifulSoup
import re
import requests
from sklearn import tree
from sklearn.preprocessing import LabelEncoder


def is_numeric(value):
    try:
        # تبدیل رشته به عدد اعشاری
        float_value = float(value)
        # اگر تبدیل موفقیت‌آمیز بود، برگرداندن True
        return True
    except ValueError:
        # در غیر این صورت، برگرداندن False
        return False


# Create your views here.
def scrap(request):
    if request.method == 'POST':
        for i in range(200):
            base_url = f'https://kilid.com/buy-apartment/tehran?page={i}'
            response = requests.get(base_url)
            if response.status_code == 200:
                soup = BeautifulSoup(response.text, 'html.parser')
                tags = soup.find_all('div',
                                     class_='flex flex-col flex-1 flex-grow h-48 min-h-[124px] justify-between pb-4')
                for tag in tags:
                    address = tag.find('p', class_='inline-flex text-grey-500').text.strip()
                    p = tag.find('span', class_='text-lg font-bold')
                    if p:
                        p = p.text.strip()
                    else:
                        p = "0"
                    price = re.search(r'\d+', p).group()
                    inner = tag.select('div.-m-2>span.text-grey-700')
                    metr = [0]
                    rooms = [0]
                    parking = [0]
                    for inn in inner:
                        s = inn.text
                        if re.search(r'متر', s):
                            metr.insert(0, re.search(r'\d+', s).group())
                        if re.search(r'خواب', s):
                            rooms.insert(0, re.search(r'\d+', s).group())
                        if re.search(r'پارکینگ', s):
                            parking.insert(0, re.search(r'\d+', s).group())

                    # اضافه کردن اطلاعات به رکورد مدل و ذخیره در پایگاه داده
                    if not house.objects.filter(location=address, metr=metr[0], parking=parking[0], rooms=rooms[0],
                                                price=price).exists():
                        h = house(location=address, metr=metr[0], parking=parking[0], rooms=rooms[0], price=price)
                        h.save()
        messages.success(request, 'ِData Scraped Successfully')
        return HttpResponseRedirect('/')
    else:
        return render(request, 'scrap.html')


def search(request):
    if request.method == 'POST':

        location = request.POST.get('location')
        price = request.POST.get('price')
        rooms = request.POST.get('rooms')
        parking = request.POST.get('parking')
        metr = request.POST.get('metr')

        # بررسی اینکه آیا هرکدام از فیلدها خالی نیست
        if location or price or rooms or parking or metr:
            filter_args = {}
            if location:
                filter_args['location'] = location
            if price:
                filter_args['price'] = price
            if rooms:
                filter_args['rooms'] = rooms
            if parking:
                filter_args['parking'] = parking
            if metr:
                filter_args['metr'] = metr

            # انجام مقایسه با اطلاعات موجود در پایگاه داده با استفاده از فیلتر
            matched_data = house.objects.filter(**filter_args)

            # ارسال نتایج به قالب
            return render(request, 'search.html', {'matched_data': matched_data})
        else:
            # اگر هیچ فیلتری مشخص نشده باشد، پیغامی نمایش داده می‌شود
            return HttpResponse("Please specify at least one filter parameter.")
    else:
        return render(request, 'search.html')


def estimate(request):
    if request.method == 'POST':
        houses = house.objects.all()
        x = []
        y = []
        for h in houses:
            if is_numeric(h.price):
                location = h.location
                if location is not None:
                    location_dummies = pd.get_dummies(location, drop_first=True)
                    all_features = np.concatenate((location_dummies.values.flatten(), [h.metr, h.rooms, h.parking]))
                    x.append(all_features)
                    y.append(h.price)
        x = np.array(x)
        y = np.array(y)

        clf = tree.DecisionTreeClassifier()
        clf = clf.fit(x, y)

        l = request.POST.get('location')
        if l is not None:
            location = pd.get_dummies(l, drop_first=True).values.flatten()
            rooms = request.POST.get('rooms')
            parking = request.POST.get('parking')
            metr = request.POST.get('metr')
            x1 = np.concatenate((location, [metr, rooms, parking])).reshape(1, -1)
            y1 = clf.predict(x1)
            context = {'price': y1[0]}
            return render(request, 'estimate.html', context)
        else:
            return HttpResponse("Invalid input for location")
    else:
        return render(request, 'estimate.html')

templates/estimate.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Web Scraping</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body class="bg-info">
<nav class="navbar navbar-default navbar-fixed-top navbar-expand-sm bg-info-subtle">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:scrap'%}">Scrap</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:search'%}">Search</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:estimate'%}">Estimate</a>
        </li>
      </ul>
    </div>
</nav>
<div class="container  bg-white m-5 p-2 border shadow-lg rounded" style="width: 100%;height: 100%;">
      <p class="text-center fw-bold">To estimate plz complete some fields so click on Estimate Button</p>
      <form action="{% url 'web:estimate' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="location" class="form-label">Location:</label>
          <input type="text" class="form-control" id="location" aria-describedby="emailHelp" name="location" required>
        </div>
        <div class="mb-3">
          <label for="metr" class="form-label">Metr:</label>
          <input type="text" class="form-control" id="metr" name="metr" required>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="room" class="form-label">Number of Rooms:</label>
            <select type="number" class="form-select" id="room" name="rooms" required>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
            </select>
          </div>
          <div class="col-md-6 mb-3">
            <label for="parking" class="form-label">Number of Parking:</label>
            <select type="number" class="form-select" id="parking" name="parking" required>
              <option value="1">0</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
            </select>
          </div>
        </div>
        <button  id="btn_estimate" type="submit" class="btn btn-block btn-info m-5" style="width: 90%; height:50px">
          Search
        </button>
      </form>
      <div id="table_estimate" class="shadow-lg border rounded m-2 p-2">
        <table class="table table-hover table-striped table-responsive">
          <thead>
            <tr>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
          <tr>
            <th scope="row"> میلیارد تومان {{price}} </th>
          </tr>
          </tbody>
        </table>
      </div>

</div>
</body>
</html>

templates/scrap.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Web Scraping</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body class="bg-info">
<nav class="navbar navbar-default navbar-fixed-top navbar-expand-sm justify-content-center bg-info-subtle">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:scrap'%}">Scrap</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:search'%}">Search</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:estimate'%}">Estimate</a>
        </li>
      </ul>
    </div>
</nav>
<div class="container  bg-white m-5 p-2 border shadow-lg rounded" style="width: 100%;height: 100%;">

  <p class="text-center fw-bold">To scraping data from website: 'https://kilid.com/' click on button</p>
  <form action="{% url 'web:scrap'%}" method="post">
    {% csrf_token %}
      <button id="btn_scrap" type="submit"  class="btn btn-block btn-info m-5" style="width: 90%; height:50px">
        Scrap
      </button>
  </form>
    {% for message in messages %}
            <div class="alert alert-{{ message.tags }} shadow-lg">
                {{ message }}
            </div>
    {% endfor %}

</div>
</body>
</html>

templates/search.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Web Scraping</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body class="bg-info">
<nav class="navbar navbar-default navbar-fixed-top navbar-expand-sm bg-info-subtle">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:scrap'%}">Scrap</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:search'%}">Search</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:estimate'%}">Estimate</a>
        </li>
      </ul>
    </div>
</nav>
<div class="container  bg-white m-5 p-2 border shadow-lg rounded" style="width: 100%;height: 100%;">
      <p class="fw-bold text-center">To search plz complete some fields so click on Search Button</p>
      <form action="{% url 'web:search' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="location" class="form-label">Location:</label>
          <input type="text" class="form-control" id="location" name="location" aria-describedby="emailHelp" required>
        </div>
        <div class="mb-3">
          <label for="metr" class="form-label">Metr:</label>
          <input type="text" class="form-control" id="metr" name="metr">
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="rooms" class="form-label">Number of Rooms:</label>
            <select type="number" class="form-select" id="rooms" name="rooms">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
            </select>
          </div>
          <div class="col-md-6 mb-3">
            <label for="parking" class="form-label">Number of Parking:</label>
            <select type="number" class="form-select" id="parking" name="parking">
              <option value="1">0</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
            </select>
          </div>
        </div>
          <div class="mb-3">
            <label for="price" class="form-label">Price:</label>
            <input type="text" class="form-control" id="price" name="price">
          </div>
        <button  id="btn_search" type="submit" class="btn btn-block btn-info m-5" style="width: 90%; height:50px">
          Search
        </button>
      </form>
      <div  id="table_search" class="shadow-lg border rounded m-2 p-2">
        <table class="table table-hover table-striped table-responsive">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Location</th>
              <th scope="col">Metr</th>
              <th scope="col">Rooms</th>
              <th scope="col">Parking</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
          {% for item in matched_data %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.location }}</td>
            <td>{{ item.metr }}</td>
            <td>{{ item.rooms }}</td>
            <td>{{ item.parking }}</td>
            <td>{{ item.price }}</td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</body>
</html>